# Generated by Django 4.1.4 on 2023-01-08 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True)),
                ('last_done_test', models.DateField(null=True)),
                ('test_count', models.IntegerField(null=True)),
                ('first_name_private', models.BooleanField(default=False)),
                ('last_name_private', models.BooleanField(default=False)),
                ('email_private', models.BooleanField(default=False)),
                ('score_private', models.BooleanField(default=False)),
                ('last_done_test_private', models.BooleanField(default=False)),
                ('test_count_private', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
