# Generated by Django 4.1.4 on 2023-01-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester_services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
